# src/ots_shared/ssh/env.py

"""OTS environment discovery, parsing, and host resolution.

Two file types mark an OTS environment directory:

``otsinfra.yaml`` (current)
    Lightweight YAML marker and metadata. Its presence signals "this is
    an OTS environment directory". Direnv handles all env vars; this file
    carries structured metadata that doesn't belong in shell state.

``.otsinfra.env`` (legacy)
    KEY=VALUE targeting context for remote execution. Still supported for
    backward compatibility — walk-up discovery falls back to it when
    ``otsinfra.yaml`` is not found.
"""

from __future__ import annotations

import ast
import ipaddress
import logging
import os
import re
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

# Re-export error types so callers (and the test suite) can import them
# from ots_shared.ssh.env alongside resolve_env_name. The canonical
# definitions live in ots_shared.ssh.hostname; this is purely an
# ergonomics re-export so a single import line covers env-name handling.
# hostname.py imports nothing from this module, so no circular risk.
from ots_shared.ssh.hostname import (
    EnvNameConflict,
    HostnameError,
    MarkerEnvNameMissing,
)

logger = logging.getLogger(__name__)

__all__ = (
    "EnvNameConflict",
    "HostnameError",
    "MarkerEnvNameMissing",
    "resolve_env_name",
)

MARKER_FILENAME = "otsinfra.yaml"
ENV_FILENAME = ".otsinfra.env"
_CONFIG_DIR_PREFIX = "config-v"
_CONFIG_SYMLINK = "config"


def _walk_up(filename: str, start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for *filename*.

    Stops at the first directory containing .git or at the user's home
    directory — whichever is reached first. Returns None if not found.
    """
    current = (start or Path.cwd()).resolve()
    home = Path.home().resolve()

    while True:
        candidate = current / filename
        if candidate.is_file():
            return candidate

        # Stop at .git boundary
        if (current / ".git").exists():
            return None

        # Stop at home directory ceiling
        if current == home:
            return None

        parent = current.parent
        # Filesystem root — stop
        if parent == current:
            return None

        current = parent


def find_marker(start: Path | None = None) -> Path | None:
    """Walk up looking for ``otsinfra.yaml``, then ``.otsinfra.env``.

    Prefers the YAML marker. Falls back to the legacy env file so
    existing environments continue to work during migration.
    """
    yaml_path = _walk_up(MARKER_FILENAME, start)
    if yaml_path is not None:
        return yaml_path
    return _walk_up(ENV_FILENAME, start)


def find_env_file(start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for a .otsinfra.env file.

    Stops at the first directory containing .git or at the user's home
    directory — whichever is reached first. Returns None if not found.

    .. deprecated:: Use :func:`find_marker` for environment directory
       discovery. This function is retained for code that specifically
       needs the KEY=VALUE env file.
    """
    return _walk_up(ENV_FILENAME, start)


def load_marker(path: Path) -> dict:
    """Load an ``otsinfra.yaml`` marker file.

    Returns a dict of the YAML contents. Uses a minimal safe loader
    that doesn't require PyYAML — the file format is simple enough
    for basic KEY: VALUE parsing. Falls back to PyYAML if available.
    """
    if not path.is_file():
        return {}

    text = path.read_text()

    # Try PyYAML first (preferred, handles all YAML)
    try:
        import yaml

        return yaml.safe_load(text) or {}
    except ImportError:
        pass

    # Minimal fallback: parse "key: value" lines with basic indentation
    # support for the nested hosts structure generated by generate_marker.
    result: dict = {}
    current_section: str | None = None
    current_key: str | None = None
    for raw_line in text.splitlines():
        stripped = raw_line.rstrip()
        if not stripped or stripped.lstrip().startswith("#"):
            continue
        if ":" not in stripped:
            continue
        indent = len(stripped) - len(stripped.lstrip())
        key, _, value = stripped.strip().partition(":")
        key = key.strip()
        value = value.strip().strip("'\"")
        if indent == 0:
            if not value:
                # Top-level section (e.g. "hosts:")
                current_section = key
                result[key] = {}
                current_key = None
            else:
                result[key] = value
                current_section = None
                current_key = None
        elif indent >= 2 and current_section and isinstance(result.get(current_section), dict):
            if indent < 4 or current_key is None:
                # Second-level key (e.g. "  db:")
                current_key = key
                if value:
                    result[current_section][key] = value
                else:
                    result[current_section][key] = {}
            else:
                # Third-level attribute (e.g. "    private_ip_address: 10.0.0.11")
                parent = result[current_section].get(current_key)
                if not isinstance(parent, dict):
                    result[current_section][current_key] = {}
                result[current_section][current_key][key] = value
    return result


_YAML_SPECIAL_CHARS = set(":#{}[]|>&*!%@'\",")


def _yaml_quote(value: str) -> str:
    """Quote a value for safe YAML output if it contains special characters."""
    if any(c in value for c in _YAML_SPECIAL_CHARS):
        # Use single quotes, escaping embedded single quotes by doubling
        return "'" + value.replace("'", "''") + "'"
    return value


def generate_marker(
    environment: str,
    *,
    hosts: dict[str, dict[str, str]] | None = None,
    **metadata: str,
) -> str:
    """Generate ``otsinfra.yaml`` content.

    Returns YAML text with ``env_name`` and ``created`` fields,
    plus any additional metadata key-value pairs. The signature
    parameter is still named ``environment`` for backward compatibility
    with ``lots init`` / ``pots init`` callers — the field on disk is
    written as ``env_name:`` per the issue #59 follow-on contract
    (single source of truth for ``parse_hostname``'s env validation).

    When *hosts* is provided, a ``hosts:`` block is appended keyed by
    role (e.g. ``db``, ``web``) with nested attributes like
    ``private_ip_address``.
    """
    lines = [
        f"env_name: {_yaml_quote(environment)}",
        f"created: '{date.today().isoformat()}'",
    ]
    for key, value in metadata.items():
        lines.append(f"{key}: {_yaml_quote(str(value))}")
    if hosts:
        lines.append("hosts:")
        for role, attrs in hosts.items():
            lines.append(f"  {role}:")
            for attr_key, attr_value in attrs.items():
                lines.append(f"    {attr_key}: {_yaml_quote(str(attr_value))}")
    lines.append("")
    return "\n".join(lines)


def create_marker(
    directory: Path,
    environment: str,
    *,
    force: bool = False,
    hosts: dict[str, dict[str, str]] | None = None,
    **metadata: str,
) -> Path:
    """Create ``otsinfra.yaml`` in *directory*.

    Returns the path to the created file.

    Raises:
        FileExistsError: If the marker already exists and *force* is False.
    """
    marker_path = directory / MARKER_FILENAME
    if marker_path.exists() and not force:
        raise FileExistsError(f"{marker_path} already exists (use --force to overwrite)")
    content = generate_marker(environment, hosts=hosts, **metadata)
    marker_path.write_text(content)
    return marker_path


GITIGNORE_FILENAME = ".gitignore"
ENVRC_FILENAME = ".envrc"

DEFAULT_HOSTS: dict[str, dict[str, str]] = {
    "jumphost": {"private_ip_address": "10.0.0.5"},
    "db": {"private_ip_address": "10.0.0.11"},
    "web": {"private_ip_address": "10.0.0.21"},
}


# Allowlisted AST node types for ``private_ip_formula`` evaluation. Anything
# not in this set (function calls, attribute access, subscripts, lambdas,
# comprehensions, etc.) is rejected before evaluation.
_FORMULA_ALLOWED_NODES: frozenset[type[ast.AST]] = frozenset(
    {
        ast.Expression,
        ast.BinOp,
        ast.UnaryOp,
        ast.Constant,
        ast.Name,
        ast.Load,
        ast.Add,
        ast.Sub,
        ast.Mult,
        ast.Div,
        ast.Mod,
        ast.FloorDiv,
        ast.LShift,
        ast.RShift,
        ast.USub,
        ast.UAdd,
    }
)


def _formula_walk(node: ast.AST, variables: Mapping[str, int | str]) -> int | str:
    """Recursive evaluator for the validated AST.

    Implements the operators in :data:`_FORMULA_ALLOWED_NODES`. Calls into
    Python operators directly rather than going through ``eval``/
    ``compile`` so the evaluator has no path to runtime code execution.
    """
    if isinstance(node, ast.Expression):
        return _formula_walk(node.body, variables)
    if isinstance(node, ast.Constant):
        # Already type-checked in _eval_formula's pre-walk pass.
        return node.value  # type: ignore[no-any-return]
    if isinstance(node, ast.Name):
        return variables[node.id]
    if isinstance(node, ast.UnaryOp):
        operand = _formula_walk(node.operand, variables)
        if not isinstance(operand, int):
            raise ValueError(f"unary operator requires int operand, got {type(operand).__name__}")
        if isinstance(node.op, ast.USub):
            return -operand
        if isinstance(node.op, ast.UAdd):
            return +operand
        raise ValueError(f"unsupported unary op: {type(node.op).__name__}")
    if isinstance(node, ast.BinOp):
        left = _formula_walk(node.left, variables)
        right = _formula_walk(node.right, variables)
        op = node.op
        # String concatenation with + is the only mixed-type operation
        # we permit; everything else requires both sides be int.
        if isinstance(op, ast.Add):
            if isinstance(left, str) or isinstance(right, str):
                return f"{left}{right}"
            return left + right
        if not (isinstance(left, int) and isinstance(right, int)):
            raise ValueError(
                f"{type(op).__name__} requires int operands, got "
                f"{type(left).__name__} and {type(right).__name__}"
            )
        if isinstance(op, ast.Sub):
            return left - right
        if isinstance(op, ast.Mult):
            return left * right
        if isinstance(op, ast.Div):
            return left // right  # integer division for IP arithmetic
        if isinstance(op, ast.FloorDiv):
            return left // right
        if isinstance(op, ast.Mod):
            return left % right
        if isinstance(op, ast.LShift):
            return left << right
        if isinstance(op, ast.RShift):
            return left >> right
        raise ValueError(f"unsupported binary op: {type(op).__name__}")
    raise ValueError(f"unreachable: unallowlisted node {type(node).__name__}")


def _eval_formula(formula: str, variables: Mapping[str, int | str]) -> str:
    """Evaluate a restricted arithmetic expression for CIDR-IP derivation.

    Supports the operators ``+ - * / // % << >>`` plus parenthesised
    sub-expressions, integer/string constants, and the names supplied in
    *variables* (typically ``ordinal``, ``region_id``, ``env_name``).

    Rejects function calls, attribute access, subscripts, lambdas,
    comprehensions, and any other node type with :class:`ValueError`
    naming the offending node — fail loud so a typo in the operator's
    formula surfaces immediately rather than silently evaluating to a
    wrong (but valid) IP. Implementation walks the validated AST
    directly; no use of ``eval``/``compile``.
    """
    try:
        tree = ast.parse(formula, mode="eval")
    except SyntaxError as exc:
        raise ValueError(f"private_ip_formula syntax error: {formula!r} ({exc})") from exc

    for node in ast.walk(tree):
        if type(node) not in _FORMULA_ALLOWED_NODES:
            raise ValueError(
                f"private_ip_formula contains forbidden node {type(node).__name__!s}: {formula!r}"
            )
        if isinstance(node, ast.Name) and node.id not in variables:
            raise ValueError(
                f"private_ip_formula references unknown name "
                f"{node.id!r}: {formula!r} (allowed: {sorted(variables)})"
            )
        if isinstance(node, ast.Constant):
            # bool is a subclass of int, so it sneaks past int|str. Reject
            # explicitly so True/False can't masquerade as 1/0 in formulas.
            if isinstance(node.value, bool) or not isinstance(node.value, int | str):
                raise ValueError(
                    f"private_ip_formula constants must be int or str, got "
                    f"{type(node.value).__name__}: {formula!r}"
                )

    return str(_formula_walk(tree, variables))


def _resolve_cidr_ip(
    cidr: str,
    ordinal: str,
    assignment: str | None,
    formula: str | None,
    marker: Mapping[str, Any],
) -> str:
    """Compute the per-ordinal IP from a host's ``private_ip_cidr``.

    ``in_order`` (default): network address + 10 + int(ordinal). Reserves
    .0–.9 for gateway and infrastructure.

    ``calculated``: requires ``private_ip_formula``. Variables exposed:
    ``ordinal: int``, ``env_name: str``, ``region_id: int`` (derived from
    the marker's ``network.ip_range`` per the per-region /16 convention).
    """
    network = ipaddress.ip_network(cidr, strict=True)
    try:
        ord_int = int(ordinal)
    except ValueError as exc:
        raise ValueError(f"ordinal must be a digit string, got {ordinal!r}") from exc

    strategy = (assignment or "in_order").strip().lower()
    if strategy == "in_order":
        host_index = 10 + ord_int
        addr = network.network_address + host_index
        if addr not in network:
            raise ValueError(f"in_order ordinal {ordinal!r} overflows {cidr} (would assign {addr})")
        return str(addr)

    if strategy == "calculated":
        if not formula:
            raise ValueError("private_ip_assignment_type='calculated' requires private_ip_formula")
        env_name_raw = marker.get("env_name") if isinstance(marker, Mapping) else None
        env_name = env_name_raw if isinstance(env_name_raw, str) else ""
        region_id = _derive_region_id(marker)
        rendered = _eval_formula(
            formula,
            {"ordinal": ord_int, "region_id": region_id, "env_name": env_name},
        )
        # Validate the rendered expression as a real IP address before
        # returning. ip_address raises ValueError on garbage. Also enforce
        # that the result lies inside the declared private_ip_cidr — a
        # formula typo that produces a syntactically valid IP outside the
        # network would otherwise return silently.
        rendered_ip = ipaddress.ip_address(rendered)
        if rendered_ip not in network:
            raise ValueError(
                f"private_ip_formula produced {rendered} outside private_ip_cidr {cidr}"
            )
        return rendered

    raise ValueError(
        f"private_ip_assignment_type must be 'in_order' or 'calculated', got {assignment!r}"
    )


def _derive_region_id(marker: Mapping[str, Any]) -> int:
    """Return ``region_id`` derived from ``network.ip_range``.

    Convention (see examples/environment/otsinfra.yaml): per-region master
    /16 sits at ``10.(100 + region_id).0.0/16``. Pull the second octet and
    subtract 100 when ``network.ip_range`` follows the pattern. Returns 0
    when no convention-matching network block is present (eu-1 grandfather).
    """
    network = marker.get("network") if isinstance(marker, Mapping) else None
    if isinstance(network, Mapping):
        raw = network.get("ip_range")
        if isinstance(raw, str):
            try:
                net = ipaddress.ip_network(raw, strict=False)
            except ValueError:
                return 0
            octets = str(net.network_address).split(".")
            if len(octets) >= 2 and octets[0] == "10":
                try:
                    second = int(octets[1])
                except ValueError:
                    return 0
                # The convention places per-region /16s at 10.(100+id).0.0/16.
                # Anything below 100 (or the impossible >255) is a non-
                # conforming range — return 0 rather than emit a negative
                # region_id that would silently corrupt formula output.
                if 100 <= second <= 255:
                    return second - 100
    return 0


def get_host_ip(marker: dict, role: str, ordinal: str = "01") -> str | None:
    """Resolve the per-ordinal private IP for *role* from loaded marker data.

    Resolution order (first non-empty wins):

    1. ``hosts.<role>.ordinals.<ordinal>.private_ip_address`` — explicit
       per-replica override.
    2. ``hosts.<role>.private_ip_address`` (legacy scalar) — only when
       ordinal is ``"01"`` so a marker carrying a single scalar continues
       to work for the canonical first instance and returns ``None`` for
       higher ordinals instead of silently aliasing.
    3. ``hosts.<role>.private_ip_cidr`` + assignment strategy — computed.

    Returns ``None`` when no source is configured. Callers that require
    a value must check and fail loud at their layer.
    """
    hosts = marker.get("hosts", {})
    if not isinstance(hosts, dict):
        # Malformed marker (hosts: as a list/scalar) — fail soft so callers
        # see the same "no IP configured" signal as a missing host entry.
        return None
    host = hosts.get(role, {})
    if not isinstance(host, dict):
        return None

    ordinals = host.get("ordinals")
    if isinstance(ordinals, dict):
        per_ord = ordinals.get(ordinal)
        if isinstance(per_ord, dict):
            override = per_ord.get("private_ip_address")
            if isinstance(override, str) and override:
                return override

    legacy = host.get("private_ip_address")
    if isinstance(legacy, str) and legacy and ordinal == "01":
        return legacy

    cidr = host.get("private_ip_cidr")
    if isinstance(cidr, str) and cidr:
        assignment = host.get("private_ip_assignment_type")
        formula = host.get("private_ip_formula")
        return _resolve_cidr_ip(
            cidr,
            ordinal,
            assignment if isinstance(assignment, str) else None,
            formula if isinstance(formula, str) else None,
            marker,
        )

    return None


def resolve_env_name(marker: Mapping[str, Any] | None) -> str:
    """Return the env name for the current shell, fail loud on conflict.

    Precedence (Option C from the issue #59 follow-on contract):

    * ``marker['env_name']`` AND ``$ENV_NAME`` set → MUST be equal;
      mismatch raises :class:`ots_shared.ssh.hostname.EnvNameConflict`.
    * Only ``marker['env_name']`` set → use it.
    * Only ``$ENV_NAME`` set OR neither set → marker is required;
      raise :class:`ots_shared.ssh.hostname.MarkerEnvNameMissing`.

    The marker is the source of truth; ``$ENV_NAME`` is the
    operator-supplied cross-check (typically set by direnv inside the
    environment dir). This helper exists so every consumer agrees on
    the precedence, instead of each CLI re-deriving it from
    ``os.environ`` and ``Path.cwd().name``.

    *marker* is typed permissively (``Mapping[str, Any] | None``) because
    callers pass in raw YAML loads — anything from a missing file
    (``None``) to a malformed scalar — and the function must coerce that
    to a typed error rather than a TypeError.
    """
    marker_value: str | None = None
    if isinstance(marker, Mapping):
        raw = marker.get("env_name")
        if isinstance(raw, str) and raw:
            marker_value = raw

    env_value = os.environ.get("ENV_NAME") or None

    if marker_value is None:
        # The contract: marker is required (even when $ENV_NAME is set).
        raise MarkerEnvNameMissing(
            "marker has no 'env_name' field; add `env_name: <env>` to otsinfra.yaml "
            "(operators may also set $ENV_NAME, but the marker is the source of truth)"
        )

    if env_value is not None and env_value != marker_value:
        raise EnvNameConflict(
            f"$ENV_NAME={env_value!r} disagrees with marker env_name={marker_value!r}; "
            "fix one or the other (the marker is the source of truth — adjust direnv "
            "or rerun in the matching environment dir)"
        )

    return marker_value


@dataclass(frozen=True, slots=True)
class MarkerNetwork:
    """Top-level ``network:`` block in ``otsinfra.yaml``.

    Holds the per-environment Hetzner network identity used by
    ``lots hcloud network ensure`` and consumed as a default by
    ``lots hcloud server create``. Semantic validation of the CIDR /
    zone is the caller's responsibility — this dataclass only enforces
    that each field is a non-empty string.
    """

    name: str
    ip_range: str
    network_zone: str


def get_network(marker: dict) -> MarkerNetwork | None:
    """Return the top-level ``network:`` block as ``MarkerNetwork``.

    Returns ``None`` when the block is absent (the caller decides
    whether that's an error). Raises :class:`KeyError` when a required
    key is missing and :class:`TypeError` when a value has the wrong
    type — Python conventional split, so callers always see a
    well-typed object or one of those two errors.
    """
    block = marker.get("network")
    if block is None:
        return None
    if not isinstance(block, dict):
        raise TypeError(f"'network' must be a mapping, got {type(block).__name__}: {block!r}")

    def _require_str(key: str) -> str:
        if key not in block:
            raise KeyError(f"network.{key} is required but missing")
        value = block[key]
        if not isinstance(value, str) or not value:
            raise TypeError(
                f"network.{key} must be a non-empty str, got {type(value).__name__}: {value!r}"
            )
        return value

    return MarkerNetwork(
        name=_require_str("name"),
        ip_range=_require_str("ip_range"),
        network_zone=_require_str("network_zone"),
    )


def generate_gitignore() -> str:
    """Generate ``.gitignore`` content for an OTS environment directory.

    Note: ``.trust/`` has its own ``.gitignore`` (created by init) so
    it's self-contained and can be deleted in one go.
    """
    lines = [
        ".envrc",
        "*.env",
        "config/",
        "gitrepo/",
        "history.db",
        "",
    ]
    return "\n".join(lines)


def create_gitignore(directory: Path, *, force: bool = False) -> Path:
    """Create ``.gitignore`` in *directory*.

    Raises:
        FileExistsError: If the file already exists and *force* is False.
    """
    path = directory / GITIGNORE_FILENAME
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists (use --force to overwrite)")
    path.write_text(generate_gitignore())
    return path


def _find_confexts(start: Path) -> Path | None:
    """Walk up from *start* looking for a sibling ``confexts/`` directory."""
    for parent in [start, *start.parents]:
        candidate = parent / "confexts"
        if candidate.is_dir():
            return candidate
    return None


def generate_envrc_template(
    cwd: Path | None = None,
    monorepo_root: Path | None = None,
) -> str:
    """Generate a template ``.envrc`` for a new OTS environment.

    Args:
        cwd: Directory where ``lots init`` is being run. Defaults to
            ``Path.cwd()``. Used to derive ``ENV_NAME``.
        monorepo_root: Base directory containing ``confexts/``. When
            ``None``, resolved by walking up from this file's location,
            then from *cwd*. Falls back to a placeholder string if not found.

    Deploy SSH keys are generated by init in ``.trust/deploy/``. The
    public half is read into ``DEPLOY_SSH_PUBKEY`` for cloud-init; the
    private path is set in ``DEPLOY_SSH_KEYFILE`` for SSH config.
    """
    resolved_cwd = cwd if cwd is not None else Path.cwd()
    env_name = resolved_cwd.name or "default"

    # Resolve confexts path: prefer monorepo_root arg, then walk from cwd,
    # then fall back to a placeholder.
    confexts_path: str
    if monorepo_root is not None:
        confexts_path = str(monorepo_root / "confexts")
    else:
        found = _find_confexts(resolved_cwd.resolve())
        confexts_path = str(found) if found else "<path-to-monorepo>/confexts"

    # Deploy keypair paths (generated by init in .trust/deploy/)
    deploy_keyfile = resolved_cwd / ".trust" / "deploy" / "ssh"
    deploy_pubkey_file = resolved_cwd / ".trust" / "deploy" / "ssh.pub"

    # SSH config path (generated by init in .ssh/)
    ssh_config_path = resolved_cwd / ".ssh" / "config"

    lines = [
        f"# {resolved_cwd / ENVRC_FILENAME}",
        "source_up",
        "",
        "# .envrc — otsinfra environment",
        f"# Created: {date.today().isoformat()}",
        "",
        'export HCLOUD_TOKEN="<paste-token-here>"',
        'export CLOUDFLARE_API_TOKEN="<paste-token-here>"',
        "",
        "# The debian system password for the regular user to be able",
        "# to sudo. Must be populated before `lots cloudinit generate`.",
        "#",
        "# Generate with: mkpasswd -m sha-512",
        'export DEPLOY_USER_PASSWD_HASH="<paste-hash-here>"',
        "",
        "# Deploy SSH keypair (generated by lots init in .trust/deploy/)",
        f'export DEPLOY_SSH_PUBKEY="$(cat {deploy_pubkey_file})"',
        f'export DEPLOY_SSH_KEYFILE="{deploy_keyfile}"',
        "",
        'export DEPLOY_USER="debian"',
        'export SSH_PORT="22"',
        'export JURISDICTION=""',
        f'export ENV_NAME="{env_name}"',
        "",
        "# Per-role tree consumed by lots confext push and lots provision push.",
        "# Point at the monorepo confexts/ directory or a standalone checkout.",
        f'export PROVISION_REPO="{confexts_path}"',
        "",
        "# Generated into ${PWD}/.ssh/config by default, but can be moved",
        "# anywhere as long as the paths in the SSH config are updated.",
        f'export SSH_CONFIG="{ssh_config_path}"',
        "",
        "# Host IPs defined in otsinfra.yaml",
        "",
    ]
    return "\n".join(lines)


def create_envrc_template(directory: Path, *, force: bool = False) -> Path:
    """Create a template ``.envrc`` in *directory*.

    Raises:
        FileExistsError: If the file already exists and *force* is False.
    """
    path = directory / ENVRC_FILENAME
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists (use --force to overwrite)")
    path.write_text(generate_envrc_template(cwd=directory))
    return path


def load_env_file(path: Path) -> dict[str, str]:
    """Parse a .otsinfra.env file into a dict.

    Format: KEY=VALUE lines. Blank lines and lines starting with # are
    ignored. Values are stripped of surrounding whitespace. Quoted values
    (single or double) are unquoted.
    """
    result: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip matching quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        result[key] = value
    return result


def resolve_host(host_flag: str | None = None) -> str | None:
    """Determine the target host using the resolution priority chain.

    Priority:
        1. Explicit --host flag value
        2. OTS_HOST environment variable
        3. OTS_HOST from .otsinfra.env (walk-up discovery)
        4. None (local execution)
    """
    # 1. Explicit flag
    if host_flag:
        logger.debug("Host from --host flag: %s", host_flag)
        return host_flag

    # 2. Environment variable
    env_host = os.environ.get("OTS_HOST")
    if env_host:
        logger.debug("Host from OTS_HOST env var: %s", env_host)
        return env_host

    # 3. Walk-up .otsinfra.env
    env_path = find_env_file()
    if env_path:
        env_vars = load_env_file(env_path)
        file_host = env_vars.get("OTS_HOST")
        if file_host:
            logger.info("Host from %s: %s", env_path, file_host)
            return file_host

    # 4. Local
    return None


def resolve_config_dir(start: Path | None = None) -> Path | None:
    """Resolve the current config directory for a jurisdiction.

    Resolution order:
        1. ``$OTS_CONFIG_DIR`` environment variable (explicit override).
        2. ``config/`` sibling to a ``otsinfra.yaml`` or ``.otsinfra.env``
           marker (walk-up discovery confirms we're in an OTS environment).
        3. OTS_TAG from ``.otsinfra.env`` → versioned directory name
           (e.g. ``v0.24`` → ``config-v0.24``). Legacy path.

    Returns the directory path if it exists, None otherwise.
    """
    # 1. Explicit env var override
    env_config_dir = os.environ.get("OTS_CONFIG_DIR")
    if env_config_dir:
        p = Path(env_config_dir)
        if p.is_dir():
            logger.debug("Config dir from $OTS_CONFIG_DIR: %s", p)
            return p
        logger.warning("$OTS_CONFIG_DIR set but not a directory: %s", p)

    # 2. Walk up to find the environment marker, then check for sibling config/
    marker_path = find_marker(start)
    if marker_path is not None:
        config_dir = marker_path.parent / _CONFIG_SYMLINK
        if config_dir.is_dir():
            logger.debug("Config dir from %s sibling: %s", marker_path.name, config_dir)
            return config_dir

    # 3. Legacy: derive from OTS_TAG in .otsinfra.env
    env_path = find_env_file(start)
    if env_path is None:
        return None

    env_vars = load_env_file(env_path)
    tag = env_vars.get("OTS_TAG")
    if not tag:
        logger.debug("No OTS_TAG in %s", env_path)
        return None

    version = _tag_to_version(tag)
    if version is None:
        logger.warning("Cannot parse version from OTS_TAG=%s in %s", tag, env_path)
        return None

    config_dir = env_path.parent / f"{_CONFIG_DIR_PREFIX}{version}"
    if config_dir.is_dir():
        logger.debug("Config dir from %s: %s", env_path, config_dir)
        return config_dir

    logger.debug("Config dir does not exist: %s", config_dir)
    return None


def generate_env_template(
    host: str = "",
    tag: str = "",
    repository: str = "",
    rabbitmq_url: str = "",
    sidecar_host_id: str = "",
) -> str:
    """Generate a .otsinfra.env template with optional pre-filled values.

    Returns the file content as a string.
    """
    lines = [
        "# .otsinfra.env — targeting context for OTS remote operations",
        "#",
        "# Walk-up discovery: rots commands search for this file",
        "# starting from the current directory upward to the repo root.",
        "",
        "# --- SSH Targeting (required) ---",
        f"OTS_HOST={host}",
        "",
        "# --- Container Image (required for deploy ops) ---",
        f"OTS_TAG={tag}",
    ]
    if repository:
        lines.append(f"OTS_REPOSITORY={repository}")

    # Sidecar section
    lines.extend(
        [
            "",
            "# --- Sidecar Configuration (optional) ---",
            "# RABBITMQ_URL: Connection string for sidecar queue communication",
            "# Format: amqp://user:pass@host:port/vhost",
        ]
    )
    if rabbitmq_url:
        lines.append(f"RABBITMQ_URL={rabbitmq_url}")
    else:
        lines.append("# RABBITMQ_URL=amqp://onetimesecret:PASS@db-host:5672/onetimesecret")

    lines.extend(
        [
            "",
            "# SIDECAR_HOST_ID: Identifier for per-host queue binding",
            "# Defaults to socket.gethostname() if not set",
        ]
    )
    if sidecar_host_id:
        lines.append(f"SIDECAR_HOST_ID={sidecar_host_id}")
    else:
        lines.append("# SIDECAR_HOST_ID=")

    lines.append("")
    return "\n".join(lines)


def validate_env_file(path: Path) -> tuple[list[str], list[str]]:
    """Validate a .otsinfra.env file for completeness.

    Returns:
        Tuple of (warnings, errors) — empty lists if valid.
    """
    warnings: list[str] = []
    errors: list[str] = []

    if not path.is_file():
        errors.append(f"Environment file not found: {path}")
        return warnings, errors

    env_vars = load_env_file(path)

    # Required for SSH targeting
    if not env_vars.get("OTS_HOST"):
        errors.append("OTS_HOST is required for remote operations")

    # Required for container operations
    if not env_vars.get("OTS_TAG"):
        warnings.append("OTS_TAG not set — container operations may use defaults")

    # Optional but recommended for sidecar
    if not env_vars.get("RABBITMQ_URL"):
        warnings.append("RABBITMQ_URL not set — sidecar will use server defaults")

    # SIDECAR_HOST_ID is optional — falls back to socket.gethostname()

    return warnings, errors


def _tag_to_version(tag: str) -> str | None:
    """Extract major.minor version from a tag string.

    Accepts formats like ``v0.24``, ``v0.24.1``, ``0.24``, ``0.24.1``.
    Returns ``"0.24"`` (major.minor only) or None if unparseable.
    """
    m = re.match(r"v?(\d+\.\d+)", tag)
    return m.group(1) if m else None


# ---------------------------------------------------------------------------
# SSH config generation
# ---------------------------------------------------------------------------

SSH_DIR = ".ssh"
SSH_CONFIG_FILENAME = "config"
SSH_KNOWN_HOSTS_FILENAME = "known_hosts"


def generate_ssh_config(
    marker: dict,
    env_name: str,
    ssh_keyfile: str,
    ssh_port: int = 22,
    username: str = "debian",
) -> str:
    """Generate SSH config content for an OTS environment.

    Args:
        marker: Loaded otsinfra.yaml data (must contain ``hosts:`` block).
        env_name: Environment name prefix for hostnames (e.g. "eu").
        ssh_keyfile: Path to SSH private key (typically ``.trust/deploy/ssh``).
        ssh_port: SSH port (default: 22).
        username: SSH username (default: debian).

    Returns:
        SSH config file content as a string.

    The jumphost gets a placeholder ``<PUBLIC_IP_AFTER_DEPLOY>`` for its
    HostName since the public IP is only known after ``lots deploy``.
    Other hosts use their private_ip_address from the marker and ProxyJump
    through the jumphost.
    """
    hosts = marker.get("hosts", {})
    if not isinstance(hosts, dict):
        hosts = {}

    ordinal = "01"

    lines = [
        f"# Auto-generated by lots init — ENV_NAME={env_name}",
        "",
    ]

    # Jumphost first (no ProxyJump, public IP placeholder)
    if "jumphost" in hosts:
        lines.extend(
            [
                f"Host {env_name}-jumphost-{ordinal}",
                "  HostName                <PUBLIC_IP_AFTER_DEPLOY>",
                "",
            ]
        )

    # Other hosts: private IP + ProxyJump through jumphost
    for role in hosts:
        if role == "jumphost":
            continue
        ip = get_host_ip(marker, role, ordinal)
        hostname = ip if ip else f"<{role.upper()}_PRIVATE_IP>"
        lines.extend(
            [
                f"Host {env_name}-{role}-{ordinal}",
                f"  HostName                {hostname}",
                f"  ProxyJump               {env_name}-jumphost-{ordinal}",
                "",
            ]
        )

    # Wildcard block with common settings
    lines.extend(
        [
            f"Host {env_name}-*",
            f"  IdentityFile              {ssh_keyfile}",
            f"  UserKnownHostsFile        {{SSH_CONFIG_DIR}}/{SSH_KNOWN_HOSTS_FILENAME}",
            f"  Port                      {ssh_port}",
            f"  User                      {username}",
            "  StrictHostKeyChecking     accept-new",
            "  SendEnv                   -LANG -LC_*",
            "  UseKeychain               yes",
            "  IdentityAgent             none",
            "  IdentitiesOnly            yes",
            "",
        ]
    )

    return "\n".join(lines)


def create_ssh_config(
    directory: Path,
    marker: dict,
    env_name: str,
    *,
    force: bool = False,
) -> Path:
    """Create SSH config and known_hosts in *directory*/.ssh/.

    Args:
        directory: Environment directory (will create .ssh/ inside).
        marker: Loaded otsinfra.yaml data.
        env_name: Environment name prefix for hostnames.
        force: Overwrite existing files if True.

    Returns:
        Path to the created SSH config file.

    The deploy keypair path is derived from the standard location
    (``.trust/deploy/ssh``) rather than passed as an argument — init
    generates it there, and the SSH config references it directly.

    Reads ``$SSH_PORT`` and ``$DEPLOY_USER`` from environment if set,
    otherwise uses defaults (22 and "debian").

    Raises:
        FileExistsError: If config already exists and *force* is False.
    """
    ssh_dir = directory / SSH_DIR
    ssh_dir.mkdir(exist_ok=True)

    config_path = ssh_dir / SSH_CONFIG_FILENAME
    if config_path.exists() and not force:
        raise FileExistsError(f"{config_path} already exists (use --force to overwrite)")

    # Deploy keypair lives at .trust/deploy/ssh (generated by init)
    deploy_keyfile = directory / ".trust" / "deploy" / "ssh"

    # Read from env vars with defaults
    ssh_port = int(os.environ.get("SSH_PORT", "22"))
    username = os.environ.get("DEPLOY_USER", "debian")

    # Generate config with actual paths and env-derived values
    content = generate_ssh_config(
        marker, env_name, str(deploy_keyfile), ssh_port=ssh_port, username=username
    )
    # Replace placeholder with actual path
    content = content.replace("{SSH_CONFIG_DIR}", str(ssh_dir))

    config_path.write_text(content)

    # Create empty known_hosts
    known_hosts_path = ssh_dir / SSH_KNOWN_HOSTS_FILENAME
    if not known_hosts_path.exists() or force:
        known_hosts_path.touch()

    return config_path


# ---------------------------------------------------------------------------
# peers.toml generation (WireGuard peer registry)
# ---------------------------------------------------------------------------

PEERS_TOML_FILENAME = "peers.toml"


def generate_peers_toml(env_name: str, deploy_wg_pubkey_path: Path) -> str:
    """Generate peers.toml content for an OTS environment.

    Args:
        env_name: Environment name (used as region name).
        deploy_wg_pubkey_path: Path to .trust/deploy/wg.pub.

    Returns:
        peers.toml file content as a string.
    """
    return f'''# {env_name}/peers.toml
#
# WireGuard peer registry for region {env_name}. Single source of truth
# driving both server-side systemd-networkd drop-ins (via `wots wireguard
# render`) and macOS/Linux client wg-quick conf (via `wots wireguard
# render-client`).
#
# See docs/research/0424-wots-package-design.md for the full schema.

[region]
name               = "{env_name}"
tunnel_subnet      = "10.100.1.0/24"
listen_port        = 58161
server_address     = "10.100.1.1/24"
# server_endpoint: replace with the public address of
# {env_name}-jumphost-01 after `lots hcloud server create`.
server_endpoint    = "<JUMPHOST_PUBLIC_IP>:58161"
# server_public_key: emitted by `wots wireguard seal-key {env_name}
# --to {env_name}-jumphost-01`; the private half is sealed into
# /etc/credstore.encrypted on the jumphost and the public half goes here.
server_public_key  = "<SERVER_PUBLIC_KEY>"
routed_subnets     = ["10.101.0.0/16"]
description        = "{env_name} region"
server_hostname    = "{env_name}-jumphost"
jumphost_hostname  = "{env_name}-jumphost-01"
persistent_keepalive = 25

# ----- Operator peer --------------------------------------------------------
#
# The deploy keypair at .trust/deploy/wg was generated by `lots init`.
# Paste the contents of {deploy_wg_pubkey_path} below.

[[peer]]
name        = "deploy"
kind        = "client"
address     = "10.100.1.2/32"
public_key  = "<DEPLOY_WG_PUBKEY>"
description = "Operator workstation"
'''


def create_peers_toml(
    directory: Path,
    env_name: str,
    *,
    force: bool = False,
) -> Path:
    """Create peers.toml in *directory*.

    Args:
        directory: Environment directory.
        env_name: Environment name.
        force: Overwrite existing file if True.

    Returns:
        Path to the created peers.toml file.

    Raises:
        FileExistsError: If file already exists and *force* is False.
    """
    path = directory / PEERS_TOML_FILENAME
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists (use --force to overwrite)")

    deploy_wg_pubkey_path = directory / ".trust" / "deploy" / "wg.pub"
    content = generate_peers_toml(env_name, deploy_wg_pubkey_path)
    path.write_text(content)
    return path
